spring.application.name=gateway-service
server.port=8080
spring.main.web-application-type=servlet

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

management.endpoints.web.exposure.include=health
